name: "research-playwight"
on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Install node
        run: nvm install 18.16.0
        run: nvm use 18.16.0

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm i && npx playwright test
